CREATE TABLE CISADM.D1_MSRMT
(
  MEASR_COMP_ID        CHAR(12 BYTE)            NOT NULL,
  MSRMT_DTTM           DATE                     NOT NULL,
  BO_STATUS_CD         CHAR(12 BYTE)            DEFAULT ' '                   NOT NULL,
  MSRMT_COND_FLG       CHAR(6 BYTE)             DEFAULT ' '                   NOT NULL,
  MSRMT_USE_FLG        CHAR(4 BYTE)             DEFAULT ' '                   NOT NULL,
  MSRMT_LOCAL_DTTM     DATE                     NOT NULL,
  MSRMT_VAL            NUMBER(16,6)             DEFAULT 0                     NOT NULL,
  ORIG_INIT_MSRMT_ID   CHAR(14 BYTE)            DEFAULT ' '                   NOT NULL,
  PREV_MSRMT_DTTM      DATE,
  MSRMT_VAL1           NUMBER(16,6)             DEFAULT 0                     NOT NULL,
  MSRMT_VAL2           NUMBER(16,6)             DEFAULT 0                     NOT NULL,
  MSRMT_VAL3           NUMBER(16,6)             DEFAULT 0                     NOT NULL,
  MSRMT_VAL4           NUMBER(16,6)             DEFAULT 0                     NOT NULL,
  MSRMT_VAL5           NUMBER(16,6)             DEFAULT 0                     NOT NULL,
  MSRMT_VAL6           NUMBER(16,6)             DEFAULT 0                     NOT NULL,
  MSRMT_VAL7           NUMBER(16,6)             DEFAULT 0                     NOT NULL,
  MSRMT_VAL8           NUMBER(16,6)             DEFAULT 0                     NOT NULL,
  MSRMT_VAL9           NUMBER(16,6)             DEFAULT 0                     NOT NULL,
  MSRMT_VAL10          NUMBER(16,6)             DEFAULT 0                     NOT NULL,
  BUS_OBJ_CD           CHAR(30 BYTE)            DEFAULT ' '                   NOT NULL,
  CRE_DTTM             DATE                     NOT NULL,
  STATUS_UPD_DTTM      DATE                     NOT NULL,
  USER_EDITED_FLG      CHAR(4 BYTE)             DEFAULT ' '                   NOT NULL,
  VERSION              NUMBER(5)                DEFAULT 1                     NOT NULL,
  LAST_UPDATE_DTTM     DATE,
  READING_VAL          NUMBER(16,6),
  COMBINED_MULTIPLIER  NUMBER(18,6),
  READING_COND_FLG     CHAR(6 BYTE)
  )